spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springsecurity"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect